### ISSUE TITLE
1.18.2 Mod Incompatibility

### ISSUE THREAD

**Issue by Raidobw2** [Siuolthepic/Soul-Ice#5] opened 2022-04-13 06:03 UTC
I've noticed that when `soulice-1.1.0+1.18.2-forge.jar` is installed with the mods (Curios)`curios-forge-1.18.2-5.0.7.0.jar` and (Sophisticated Backpacks)`sophisticatedbackpacks-1.18.2-3.15.17.559.jar` on Forge `40.0.45` for Minecraft `1.18.2`, the 'B' keybind to open the backpack and the Curios button in the inventory no longer work. The backpack also cannot be opened by right-click with it in hand while looking at air.
When (The One Probe)`theoneprobe-1.18-5.1.0.jar` is installed as well, the current block you're looking at is no longer shown on screen.

In short, these mods stop working completely when Soul Ice is installed. I am thinking it could be the `onCustomPayload` mixin that could be causing this. I know nothing about modded, but does it need the `ci.cancel();`?
https://github.com/Siuolthepic/Soul-Ice/blob/40975de1b47f112c4350dd695e79e100cfc30448/forge/src/main/java/io/siuolplex/soul_ice/forge/mixin/ClientPlayNetworkHandlerMixin.java#L29-L47

Also this seems to be the only relevant-ish information in the `debug.log`:
```
[13Apr2022 01:55:04.947] [Netty Local Client IO #0/DEBUG] [mixin/]: Mixing ClientPlayNetworkHandlerMixin from soul_ice.forge.mixins.json into net.minecraft.client.multiplayer.ClientPacketListener
[13Apr2022 01:55:04.948] [Netty Local Client IO #0/DEBUG] [mixin/]: Renaming synthetic method lambda$soulIce$catchPackets$3()V to md12ebca$lambda$soulIce$catchPackets$3$0 in soul_ice.forge.mixins.json:ClientPlayNetworkHandlerMixin
[13Apr2022 01:55:04.948] [Netty Local Client IO #0/DEBUG] [mixin/]: Renaming synthetic method lambda$soulIce$catchPackets$2(Z)V to md12ebca$lambda$soulIce$catchPackets$2$1 in soul_ice.forge.mixins.json:ClientPlayNetworkHandlerMixin
[13Apr2022 01:55:04.948] [Netty Local Client IO #0/DEBUG] [mixin/]: Renaming synthetic method lambda$soulIce$catchPackets$1(Z)V to md12ebca$lambda$soulIce$catchPackets$1$2 in soul_ice.forge.mixins.json:ClientPlayNetworkHandlerMixin
[13Apr2022 01:55:04.948] [Netty Local Client IO #0/DEBUG] [mixin/]: Renaming synthetic method lambda$soulIce$catchPackets$0(F)V to md12ebca$lambda$soulIce$catchPackets$0$3 in soul_ice.forge.mixins.json:ClientPlayNetworkHandlerMixin
```

I'm looking forward to continue using the mod since it adds a lot of cool blocks and enchantments, so I hope this can be fixed! Thanks in advance

**Comment by Siuolplex** [comment] 2022-05-15 18:08
I just saw this, sorry for ultra late response, Ill be looking into it.

**Comment by Siuolplex** [comment] 2022-05-15 21:13
First half of the issue has been confirmed and fixed on my pc, your hypothesis on why was correct as well! I am a lil surprised if I am to be completely honest. Ill try to notify the person whos mixin that code is based on.

Ill try and see about TheOneProbe's issue and see if its related

**Comment by Raidobw2** [comment] 2022-05-15 21:18
Happy to see you managed to fix part of it :) Thanks for the information! I'll stay tuned for any more news

**Comment by Siuolplex** [comment] 2022-05-15 21:20
Alright, just finished looking at The One Probe and it seems to be fixed as well! It seems like its all working properly. Ill put this in 1.3.0 when I release it (Hopefully later today)

**Comment by Siuolplex** [comment] 2022-05-16 02:49
Newest commit fixes this! Ill be releasing the associated version of the mod within the next half an hour, thank you a ton!

**Closed as completed by Siuolplex** 2022-05-16 02:49 UTC
Labels: bug, good first issue

**Comment by Raidobw2** [comment] 2022-05-16 04:27
That's awesome! Thanks a bunch :) I was about to test this but it looks like there's another small mixin issue on startup, I'll make you another issue for it in a minute
